notifications:
  email: false

language: python

install:
  - "sudo apt-get install flac"
  - "sudo apt-get install mp3val"
  - "sudo apt-get install oggz-tools"
  - "pip install coveralls"

script: tox

after_success: coveralls
