notifications:
  email: false

language: python

install:
  - "sudo apt-get install flac"
  - "sudo apt-get install mp3val"
  - "sudo apt-get install oggz-tools"
  - "pip install git+git://github.com/sampsyo/beets.git@master"
  - "pip install coveralls"
  - "pip install ."

script: nosetests

after_success: coveralls
