notifications:
  email: false

language: python

install:
  - "pip install git+git://github.com/geigerzaehler/beets.git@check-plugin"
  - "pip install coveralls"
  - "pip install ."

script: nosetests

after_success: coveralls
