notifications:
  email: false

language: python

install:
  - "pip install git+git://github.com/sampsyo/beets.git@master"
  - "pip install coveralls"
  - "pip install ."

script: nosetests

after_success: coveralls
